# Generated by Django 2.2.6 on 2019-11-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Uploader_name', models.CharField(max_length=50)),
                ('Name_of_movie', models.CharField(max_length=50)),
                ('Genre_of_movie', models.TextField()),
                ('Thumbnail', models.ImageField(upload_to='movies/Images')),
                ('Video_clip', models.FileField(upload_to='movies')),
            ],
        ),
        migrations.CreateModel(
            name='webSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Uploader_name', models.CharField(max_length=50)),
                ('Name_of_webSeries', models.CharField(max_length=50)),
                ('Genre_of_webSeries', models.TextField()),
                ('Thumbnail', models.ImageField(upload_to='webSeries/Images')),
                ('Video_clip', models.FileField(upload_to='webSeries')),
            ],
        ),
    ]
