# Generated by Django 2.2.6 on 2019-11-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcix', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='Duration_of_movie',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='movies',
            name='Rating',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='webseries',
            name='Duration_of_each_episode',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='webseries',
            name='Number_of_Seasons',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='webseries',
            name='Number_of_each_season_episode',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='webseries',
            name='Rating',
            field=models.IntegerField(default=10),
        ),
    ]
